"use client";

import { FormEvent, useEffect, useState } from "react";
import { Boxes, X } from "lucide-react";

type Product = { id: string; name: string; sku: string; stock: number };
export function InventoryAdjustModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [productVariantId, setProductVariantId] = useState(""); const [direction, setDirection] = useState("IN"); const [quantity, setQuantity] = useState("1"); const [reason, setReason] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/catalog").then((response) => response.ok ? response.json() : null).then((data) => setProducts(data?.products ?? [])).catch(() => undefined); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/inventory/adjust", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ productVariantId, direction, quantity: Number(quantity), reason }) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "Adjustment failed"); return; } onSaved(); onClose(); }
  return <div className="modal-backdrop"><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-header"><div className="modal-icon"><Boxes size={18} /></div><div><h2>Adjust inventory</h2><p>Every adjustment is recorded in the movement ledger.</p></div><button className="icon-button modal-close" onClick={onClose} aria-label="Close"><X size={18} /></button></div><form onSubmit={submit}><div className="sale-fields"><label>Product<select value={productVariantId} onChange={(event) => setProductVariantId(event.target.value)} required><option value="">Select product</option>{products.map((product) => <option value={product.id} key={product.id}>{product.name} · {product.sku} · {product.stock} in stock</option>)}</select></label><label>Direction<select value={direction} onChange={(event) => setDirection(event.target.value)}><option value="IN">Add stock</option><option value="OUT">Remove stock</option></select></label><label>Quantity<input type="number" min="1" step="1" value={quantity} onChange={(event) => setQuantity(event.target.value)} required /></label><label>Reason<input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Why is stock changing?" required /></label>{error && <p className="form-error">{error}</p>}</div><div className="modal-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" className="primary-button">Save adjustment</button></div></form></section></div>;
}
